using System;
using NUnit.Framework;
using System.Collections.Generic;
using System.Linq;
using TestGeneratorLibrary;

namespace Class1Test
{
    [TestFixture]
    public class Class1
    {
        [Test]
        public void MyMethodTest()
        {
            int a = ;
            int b = ;
            void actual = MyMethod(a, b);
            int expected = 0;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        [Test]
        public void MyMethod1Test()
        {
            object actual = MyMethod1();
            int expected = 0;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}