using System;
using NUnit.Framework;
using System.Collections.Generic;
using System.Linq;
using TestGeneratorLibrary;

namespace Class2Test
{
    [TestFixture]
    public class Class2Test
    {
        private Class2 _class2;
        [SetUp]
        public void SetUp()
        {
            var list = default(List<int>);
            _class2 = new Class2(list);
        }

        [Test]
        public void MyMethodTest()
        {
            List<int> list = default(List<int>);
            Class1 actual = _class2.MyMethod(list);
            int expected = 0;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}