using System;
using NUnit.Framework;
using System.Collections.Generic;
using System.Linq;
using TestGeneratorLibrary;
using Moq;

namespace Class1Test
{
    [TestFixture]
    public class Class1Test
    {
        private Class1 _class1;
        [SetUp]
        public void SetUp()
        {
            var str = default(string);
            _class1 = new Class1(str);
        }

        [Test]
        public void MyMethodTest()
        {
            int a = default(int);
            int b = default(int);
            _class1.MyMethod(a, b);
            Assert.Fail("autogenerated");
        }

        [Test]
        public void MyMethod1Test()
        {
            object actual = _class1.MyMethod1();
            int expected = 0;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}